######### Optimized for Tablet Kiosk mode 10.1"/10.4" 1920x1200  ################# 

                    
#########################   SIDEBAR      ###################################
sidebar: !include views/sidebar.yaml

####################### TEMPLATE BUTTON CARD ################################
button_card_templates: !include configurations/general/button_card_templates.yaml

title: Casa
kiosk_mode:
  hide_header: true
views:
########################### SCHEDA HOME ####################################
  - title: Home
    path: home
    panel: true  
    badges: []
    cards:
      - !include views/home.yaml
   
########################### SCHEDA PULIZIA #################################
  - title: Pulizia
    path: pulizia
    panel: true
    badges: []
    cards:
      - !include views/pulizia.yaml 

########################### SCHEDA MUSICA ##################################     
  - title: Musica
    path: musica
    panel: true
    badges: [] 
    cards:
      - !include views/musica.yaml
     
########################### SCHEDA METEO ###################################
  - title: Meteo
    path: meteo 
    panel: true
    badges: []
    cards: 
      - !include views/meteo.yaml

########################### SCHEDA DISPOSITIVI #############################
  - title: Dispositivi   
    path: dispositivi 
    panel: true
    badges: []
    cards:   
      - !include views/dispositivi.yaml  
########################### SCHEDA MONITORING #################################
  - title: Monitoring  
    path: monitoring  
    panel: true 
    badges: []
    cards: 
      - !include views/monitoring.yaml                                                                              
########################### SCHEDA GARDEN #################################
  - title: Giardino  
    path: garden  
    panel: true
    badges: []
    cards:
      - !include views/garden.yaml         
                                  